MDFloatLayout:
    radius: [5, 0, 0, 0]
    md_bg_color: app.theme_cls.primary_color
    
    MDLabel:
        text: "6 DOF Robot Interface Controller"
        halign: "center"
        size_hint: 1, 1
        pos_hint:{"center_x": .5, "center_y": 0.95}

    MDRaisedButton:
        text: "Publish!"
        md_bg_color: "green"
        halign: "center"
        size_hint: 0.15, 0.05
        pos_hint:{"center_x": .5, "center_y": 0.1}

