# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from jkprobot/Ardubot.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Ardubot(genpy.Message):
  _md5sum = "416e94e338a7777f87f98090399f3e9b"
  _type = "jkprobot/Ardubot"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 base_deg
int32 waist_deg
int32 shoulder_deg
int32 wrist_deg
int32 grip_deg"""
  __slots__ = ['base_deg','waist_deg','shoulder_deg','wrist_deg','grip_deg']
  _slot_types = ['int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       base_deg,waist_deg,shoulder_deg,wrist_deg,grip_deg

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Ardubot, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.base_deg is None:
        self.base_deg = 0
      if self.waist_deg is None:
        self.waist_deg = 0
      if self.shoulder_deg is None:
        self.shoulder_deg = 0
      if self.wrist_deg is None:
        self.wrist_deg = 0
      if self.grip_deg is None:
        self.grip_deg = 0
    else:
      self.base_deg = 0
      self.waist_deg = 0
      self.shoulder_deg = 0
      self.wrist_deg = 0
      self.grip_deg = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5i().pack(_x.base_deg, _x.waist_deg, _x.shoulder_deg, _x.wrist_deg, _x.grip_deg))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.base_deg, _x.waist_deg, _x.shoulder_deg, _x.wrist_deg, _x.grip_deg,) = _get_struct_5i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5i().pack(_x.base_deg, _x.waist_deg, _x.shoulder_deg, _x.wrist_deg, _x.grip_deg))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.base_deg, _x.waist_deg, _x.shoulder_deg, _x.wrist_deg, _x.grip_deg,) = _get_struct_5i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5i = None
def _get_struct_5i():
    global _struct_5i
    if _struct_5i is None:
        _struct_5i = struct.Struct("<5i")
    return _struct_5i
