controller_list:
  - name: fake_Thangs5dof_controller
    type: $(arg fake_execution_type)
    joints:
      - waist
      - shoulder
      - elbow
      - wrist_yaw
      - wrist_pitch
initial:  # Define initial robot poses per group
#  - group: Thangs5dof
#    pose: home

  []