Thangs5dof_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - elbow
    - shoulder
  gains:
    elbow:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - end_effector
    - waist
  gains:
    end_effector:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    waist:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
end_effector_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - end_effector
  gains:
    end_effector:
      p: 100
      d: 1
      i: 1
      i_clamp: 1