controller_list:
  - name: Thangs5dof_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - elbow
      - shoulder
      - waist
      - wrist_yaw
      - wrist_pitch