onshape:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Position Controllers ---------------------------------------
      waist_position_controller:
        type: effort_controllers/JointPositionController
        joint: waist
        pid: {p: 1.0, i: 1.0, d: 0.0}